// Login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCEED = 'LOGIN_SUCCEED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_REQUEST_ENDED = 'LOGIN_REQUEST_ENDED';

// Logout
export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_REQUEST_SUCCED = 'LOGOUT_REQUEST_SUCCED';
export const LOGOUT_REQUEST_FAILED = 'LOGOUT_REQUEST_FAILED';
export const LOGOUT_REQUEST_ENDED = 'LOGOUT_REQUEST_ENDED';
