// Fetch from database
export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_REQUEST_SUCCED = 'FETCH_REQUEST_SUCCED';
export const FETCH_REQUEST_FAILED = 'FETCH_REQUEST_FAILED';
export const FETCH_REQUEST_ENDED = 'FETCH_REQUEST_ENDED';