// fetch userSession
export const FETCH_USERSESSION = 'FETCH_USERSESSION';
export const FETCH_USERSESSION_SUCCED = 'FETCH_USERSESSION_SUCCED';
export const FETCH_USERSESSION_FAILED = 'FETCH_USERSESSION_FAILED';
export const FETCH_USERSESSION_ENDED = 'FETCH_USERSESSION_ENDED';

// update userSession
export const UPDATE_USERSESSION = 'UPDATE_USERSESSION';
export const UPDATE_USERSESSION_SUCCED = 'UPDATE_USERSESSION_SUCCED';
export const UPDATE_USERSESSION_FAILED = 'UPDATE_USERSESSION_FAILED';
export const UPDATE_USERSESSION_ENDED = 'UPDATE_USERSESSION_ENDED';