// fetch userSession
export const FETCH_USERSESSION = 'FETCH_USERSESSION';
export const FETCH_USERSESSION_SUCCED = 'FETCH_USERSESSION_SUCCED';
export const FETCH_USERSESSION_FAILED = 'FETCH_USERSESSION_FAILED';
export const FETCH_USERSESSION_ENDED = 'FETCH_USERSESSION_ENDED';

// update userSession
export const UPDATE_USERSESSION = 'UPDATE_USERSESSION';
export const UPDATE_USERSESSION_SUCCED = 'UPDATE_USERSESSION_SUCCED';
export const UPDATE_USERSESSION_FAILED = 'UPDATE_USERSESSION_FAILED';
export const UPDATE_USERSESSION_ENDED = 'UPDATE_USERSESSION_ENDED';

// Upload profile picture
export const UPLOAD_PROFILE_PICTURE = 'UPLOAD_PROFILE_PICTURE';
export const UPLOAD_PROFILE_PICTURE_SUCCED = 'UPLOAD_PROFILE_PICTURE_SUCCED';
export const UPLOAD_PROFILE_PICTURE_FAILED = 'UPLOAD_PROFILE_PICTURE_FAILED';
export const UPLOAD_PROFILE_PICTURE_ENDED = 'UPLOAD_PROFILE_PICTURE_ENDED';

// Listen picture change
export const START_LISTEN_PICTURE_CHANGE = 'START_LISTEN_PICTURE_CHANGE';
export const LISTENING_PICTURE_CHANGE = 'LISTENING_PICTURE_CHANGE';
export const STOP_LISTEN_PICTURE_CHANGE = 'STOP_LISTEN_PICTURE_CHANGE';
